/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.proyecto2805;

import java.util.Scanner;

// EJERCICIOS JOSUÉ

public class App {
    public String getGreeting() {
        return "Hola Josué";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("hola munfo2");
        tabla_multiplicar();
    }
    public static void tabla_multiplicar(){
        System.out.println("TABLA DE MULTIPLICAR DE UN NÚMERO");
        System.out.println("Ingrese un número para mostrar su tabla");
        Scanner sc = new Scanner(System.in);
        int numero = sc.nextInt();
        
        
        for (int i = 1; i <= 12; i++) {
            int multi = i*numero;
            System.out.println("La multiplicacion de "+ i + " por " + numero + " es igual a " + multi);
        
        
            
        }
        
    }

    public class HolaMundoPersonalizado {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.print("Ingresa tu nombre: ");
            String nombre = scanner.nextLine();
            
            System.out.println("¡Hola, " + nombre + "! Bienvenido/a a Java.");
        }
    }

    public class ParOImpar {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.print("Ingresa un número entero: ");
            int numero = scanner.nextInt();
            
            if (numero % 2 == 0) {
                System.out.println("El número " + numero + " es par.");
            } else {
                System.out.println("El número " + numero + " es impar.");
            }
        }
    }
}
}
    
}
