/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.proyecto2805;

import java.util.Scanner;

// EJERCICIOS JOSUÉ

public class App {
    public String getGreeting() {
        return "Hola Josué";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("hola munfo2");
        tabla_multiplicar();
    }
    public static void tabla_multiplicar(){
        System.out.println("TABLA DE MULTIPLICAR DE UN NÚMERO");
        System.out.println("Ingrese un número para mostrar su tabla");
        Scanner sc = new Scanner(System.in);
        int numero = sc.nextInt();
        
        
        for (int i = 1; i <= 12; i++) {
            int multi = i*numero;
            System.out.println("La multiplicacion de "+ i + " por " + numero + " es igual a " + multi);
        
        
            
        }
        
    }

    public class HolaMundoPersonalizado {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.print("Ingresa tu nombre: ");
            String nombre = scanner.nextLine();
            
            System.out.println("¡Hola, " + nombre + "! Bienvenido/a a Java.");
        }
    }

    public class ParOImpar {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.print("Ingresa un número entero: ");
            int numero = scanner.nextInt();
            
            if (numero % 2 == 0) {
                System.out.println("El número " + numero + " es par.");
            } else {
                System.out.println("El número " + numero + " es impar.");
            }
        }
    }
}
}
    
}

//codigos damaris :D
// ============================================
// 1. MAYOR DE EDAD
// ============================================
import java.util.Scanner;

public class MayorDeEdad {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("=== MAYOR DE EDAD ===");
        System.out.print("¿Cuántos años tienes? ");
        int edad = scanner.nextInt();

        if (edad >= 18) {
            System.out.println("Eres MAYOR de edad.");
        } else {
            System.out.println("Eres MENOR de edad.");
            System.out.println("Te faltan " + (18 - edad) + " años para ser mayor.");
        }

        scanner.close();
    }
}

// ============================================
// 2. CONTAR DEL 1 AL 10
// ============================================
public class ContarNumeros {
    public static void main(String[] args) {

        System.out.println("=== CONTANDO DEL 1 AL 10 ===");

        for (int i = 1; i <= 10; i++) {
            System.out.println("Número: " + i);
        }

        System.out.println("¡Listo!");
    }
}

// ============================================
// 3. NÚMERO POSITIVO O NEGATIVO
// ============================================
import java.util.Scanner;

public class PosNeg {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Ingresa un número: ");
        int numero = scanner.nextInt();

        if (numero > 0) {
            System.out.println("El número es POSITIVO.");
        } else if (numero < 0) {
            System.out.println("El número es NEGATIVO.");
        } else {
            System.out.println("El número es CERO.");
        }

        scanner.close();
    }
}

//Ejercicio Liliana 

//1. Area de un Circulo

public class AreadeunCirculo{
    public static void main(String[] args) {
        Scanner sc = new Scanner (System.in);
        
        // area de un circulo 
        
       //radio del circulo
       
        System.out.println("algoritmo para calcular el area de un circulo");
        System.out.println("ingrese el radio");
        double radio=sc.nextDouble();//guardando el radio
         
        double area = Math.PI * radio * radio;
        
        System.out.println("el area de un circulo es"+ area);
       
    }
  }
}

 //2. Una persona puede votar 

import java.util.Scanner;

public class VOTAR {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.println("Ingrese su edad");
        int edad = sc.nextInt();

        if (edad >= 18) {
            System.out.println("Puede votar");
        } else {
            System.out.println("No puede votar");
        }
    }
}
//3.Suma de numeros del 1 al N
public class SumarNumeros {
   

    public static void main(String[] args){
    
      
        Scanner sc= new Scanner(System.in);{
            //sumar numeros del 1 hasta N
            // Pedir al estudiante  que ingrese el valor de N
            System.out.print("Ingrese el valor de N: ");
            int n = sc.nextInt();
            // Variable para almacenar la suma acumulada
            int suma = 0;
            // Bucle que recorre desde 1 hasta N y suma cada número
            for (int i = 1; i <= n; i++) {
                suma = suma + i; // Acumular el valor actual en la suma
            }  // Mostrar el resultado final
            System.out.println("La suma de los números del 1 hasta " + n + " es: " + suma);
           
        }
     }
 }
